### ISSUE TITLE
发布订单输入特殊字符时，出现“server error”提示

### ISSUE THREAD

**Issue by auhig** [auhig/bag-bug#99]
![screenshot_2014-12-31-21-42-22](https://cloud.githubusercontent.com/assets/685821/5587996/8e301992-9137-11e4-87c4-38f8ed7cf1b9.png)
![screenshot_2014-12-31-21-42-29](https://cloud.githubusercontent.com/assets/685821/5587997/8e66d3ce-9137-11e4-82fd-63f31c1937d0.png)

**Comment by ByronWang** [comment]
不处理，服务器端把这个错误记录在案而已。
